name: Build and push to Docker Hub as outlandish/wordpress-dev:8.1

on:
  push:
    branches: [master, php8.1]
  schedule:
    - cron: '17 3 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: outlandish/wordpress-dev:8.1
